export const products = [
  {
    id: 1,
    name: "MNBVCXZ Watch Bands Compatible for Apple Watch Band",
    image: "/rolex4.png",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: true,
  },
  {
    id: 2,
    name: "MNBVCXZ Watch Bands Compatible for Apple Watch Band",
    image: "/rolex3.jpg",
    price: 500,
    brand: "Rolex",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: true,
  },
  {
    id: 3,
    name: "Rolex",
    image: "/rolex4.png",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 4,
    name: "Rolex",
    image: "/rolex4.png",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 5,
    name: "Rolex",
    image: "rolex2.jpg",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 6,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 7,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 8,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 9,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 10,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 11,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 12,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 13,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 14,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 15,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 16,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 17,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 18,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 19,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 20,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 21,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 22,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 23,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 24,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 25,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 26,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 27,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 28,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 29,
    name: "Rolex",
    image: "",
    price: 500,
    brand: "",
    description: "",
    seller: "",
    category: "watch",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
  {
    id: 30,
    name: "",
    image: "",
    price: 0,
    brand: "",
    description: "",
    seller: "",
    category: "",
    discount: 10,
    imported: "USA",
    model: "rolex523g",
    note: "Step Down Voltage Transformer required for using electronics products of US store (110-120). Recommended power converters",
    inStock: false,
  },
];
